sudo: false
os:
  - linux
language: python
python:
  - 3.6
install:
  - pip install pipenv
  - pipenv install --dev --skip-lock
script:
  - pytest --cov
after_success:
  - coverage xml -o coverage.xml
  - python-codacy-coverage -r coverage.xml
notifications:
  email:
    on_success: never
    on_failure: always
